Fix build failure in readline lib
This is a backported patch from gdb upstream, see the commit
425f843d58c5 ("Import GNU Readline 8.2"), and only backported
patch related to compilation errors.

Without the patch:

  signals.c: In function ‘_rl_handle_signal’:
  signals.c:62:36: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]
     62 | #  define SIGHANDLER_RETURN return (0)
        |                                    ^
  signals.c:290:3: note: in expansion of macro ‘SIGHANDLER_RETURN’
    290 |   SIGHANDLER_RETURN;
        |   ^~~~~~~~~~~~~~~~~
  signals.c:178:1: note: declared here
    178 | _rl_handle_signal (int sig)
        | ^~~~~~~~~~~~~~~~~
  signals.c: In function ‘rl_sigwinch_handler’:
  signals.c:306:32: error: passing argument 2 of ‘rl_set_sighandler’ from incompatible pointer type [-Wincompatible-pointer-types]
    306 |   rl_set_sighandler (SIGWINCH, rl_sigwinch_handler, &dummy_winch);
        |                                ^~~~~~~~~~~~~~~~~~~
        |                                |
        |                                void (*)(int)
  In file included from rldefs.h:31,
                   from signals.c:37:
  signals.c:81:51: note: expected ‘void (*)(void)’ but argument is of type ‘void (*)(int)’
     81 | static SigHandler *rl_set_sighandler PARAMS((int, SigHandler *, sighandler_cxt *));

Note: the current build failure was observed on gcc (GCC) 15.0.0.

Signed-off-by: Lianbo Jiang <lijiang@redhat.com>