Makefile: Fix build failure with "make -j jobs" option
The "make -j jobs" option sometimes fails with an error like this:

  $ make clean ; make -j $(nproc) warn
  ...
  ar: creating crashlib.a
    CXXLD  gdb
  /usr/bin/ld: ../../crashlib.a(main.o): in function `dump_build_data':
  /home/crash/main.c:1829: undefined reference to `build_command'
  /usr/bin/ld: /home/crash/main.c:1830: undefined reference to `build_data'
  collect2: error: ld returned 1 exit status
  make[4]: *** [Makefile:1872: gdb] Error 1
  make[3]: *** [Makefile:10072: all-gdb] Error 2
  make[2]: *** [Makefile:860: all] Error 2
  crash build failed

This is because build_data.c is compiled by two jobs and they write to
build_data.o simultaneously and break it. Remove one of them.

Signed-off-by: Kazuhito Hagio <k-hagio-ab@nec.com>
Signed-off-by: Lianbo Jiang <lijiang@redhat.com>