Fix build failure on 32bit machine(i686)
This issue was caused by commit 0f39e33d3504 with the following
compilation error:

  frame.c: In function ‘CORE_ADDR frame_unwind_pc(frame_info*)’:
  frame.c:982:35: error: cannot convert ‘CORE_ADDR*’ {aka ‘long long unsigned int*’} to ‘ulong*’ {aka ‘long unsigned int*’}
    982 |           crash_decode_ptrauth_pc(&pc);
        |                                   ^~~
        |                                   |
        |                                   CORE_ADDR* {aka long long unsigned int*}
  frame.c:948:48: note: initializing argument 1 of ‘void crash_decode_ptrauth_pc(ulong*)’
    948 | extern "C" void crash_decode_ptrauth_pc(ulong* pc);
        |                                         ~~~~~~~^~

Fixes: 0f39e33d3504 ("arm64: add pac mask to better support gdb stack unwind")
Reported-by: Guanyou.Chen <chenguanyou@xiaomi.com>
Signed-off-by: Lianbo Jiang <lijiang@redhat.com>