LoongArch64: Fixed link errors when build on LOONGARCH64 machine
The following link error exists when building with LOONGARCH64
machine:

/usr/bin/ld: proc-service.o: in function `.LVL71':
proc-service.c:(.text+0x324): undefined reference to `fill_gregset ...
/usr/bin/ld: proc-service.o: in function `.LVL77':
proc-service.c:(.text+0x364): undefined reference to `supply_gregset ...
/usr/bin/ld: proc-service.o: in function `.LVL87':
proc-service.c:(.text+0x3c4): undefined reference to `fill_fpregset ...
/usr/bin/ld: proc-service.o: in function `.LVL93':
proc-service.c:(.text+0x404): undefined reference to `supply_fpregset
collect2: error: ld returned 1 exit status

The cause of the error is that the definition of a function such as
fill_gregset is not implemented. This patch is used to fix this error.

[ kh: added rm command for gdb files added and modified multiple times. ]

Reported-by: Xiujie Jiang <jiangxiujie@kylinos.cn>
Signed-off-by: Ming Wang <wangming01@loongson.cn>
Signed-off-by: Kazuhito Hagio <k-hagio-ab@nec.com>