Fix compilation error and warning with gcc-4.8.5
Fix the following compilation error in diskdump.c and warning in
xen_hyper.c with gcc-4.8.5 (e.g. RHEL7).

- diskdump.c: In function 'try_zram_decompress':
  diskdump.c:3048:3: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int count = 0; count < PAGESIZE() / sizeof(ulong); count++) {
     ^
  diskdump.c:3048:3: note: use option -std=c99 or -std=gnu99 to compile your code
  make[4]: *** [diskdump.o] Error 1
  make[3]: *** [gdb] Error 2
  make[2]: *** [rebuild] Error 2
  make[1]: *** [gdb_merge] Error 2
  make: *** [all] Error 2

- xen_hyper.c: In function 'xen_hyper_x86_pcpu_init':
  xen_hyper.c:387:36: warning: 'init_tss' may be used uninitialized in this function [-Wmaybe-uninitialized]
      xen_hyper_store_pcpu_context_tss(pcc, init_tss, buf);
                                      ^

Fixes: 0172e35083b5 ("Fix "rd" command to display data on zram on Linux 5.17 and later")
Fixes: 9ee564cd1a46 ("xen: get stack address via stack_base array if available")
Signed-off-by: Kazuhito Hagio <k-hagio-ab@nec.com>